package panels;

import javax.swing.JLabel;

/**
 * Form that lets the user introduce an empoyee's attributes.
 *
 * @author Gustavo
 * @version 1.0 29/6/2020
 */
public class PersonAttributes
  extends javax.swing.JPanel
{
    public PersonAttributes ()
    {
        super ();
        initComponents ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        titleBar = new components.TitleBanner();
        attributesPanel = new javax.swing.JPanel();
        labelRut = new javax.swing.JLabel();
        labelPaterno = new javax.swing.JLabel();
        inputPaterno = new javax.swing.JTextField();
        labelMaterno = new javax.swing.JLabel();
        inputMaterno = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        buttonTest = new javax.swing.JButton();
        inputRut = new components.GTextField();

        setBackground(resources.Gui.BEIGE);
        setLayout(new java.awt.GridBagLayout());

        titleBar.setTitle("Ingrese los datos del empleado.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(titleBar, gridBagConstraints);

        attributesPanel.setBackground(resources.Gui.BEIGE);
        attributesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        attributesPanel.setLayout(new java.awt.GridBagLayout());

        labelRut.setFont(fonts.Fonts.TEXT);
        labelRut.setForeground(resources.Gui.DARK_SLATE_GRAY);
        labelRut.setText("Rut:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        attributesPanel.add(labelRut, gridBagConstraints);

        labelPaterno.setFont(fonts.Fonts.TEXT);
        labelPaterno.setForeground(resources.Gui.DARK_SLATE_GRAY);
        labelPaterno.setText("Apellido paterno:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        attributesPanel.add(labelPaterno, gridBagConstraints);

        inputPaterno.setBackground(resources.Gui.DARK_BLUE);
        inputPaterno.setFont(fonts.Fonts.TEXT);
        inputPaterno.setForeground(resources.Gui.BEIGE);
        inputPaterno.setSelectedTextColor(resources.Gui.DARK_BLUE);
        inputPaterno.setSelectionColor(resources.Gui.MIDNIGHT_BLUE);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        attributesPanel.add(inputPaterno, gridBagConstraints);

        labelMaterno.setFont(fonts.Fonts.TEXT);
        labelMaterno.setForeground(resources.Gui.DARK_SLATE_GRAY);
        labelMaterno.setText("Apellido materno:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        attributesPanel.add(labelMaterno, gridBagConstraints);

        inputMaterno.setBackground(resources.Gui.DARK_BLUE);
        inputMaterno.setFont(fonts.Fonts.TEXT);
        inputMaterno.setForeground(resources.Gui.BEIGE);
        inputMaterno.setSelectedTextColor(resources.Gui.DARK_BLUE);
        inputMaterno.setSelectionColor(resources.Gui.MIDNIGHT_BLUE);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        attributesPanel.add(inputMaterno, gridBagConstraints);

        labelName.setFont(fonts.Fonts.TEXT);
        labelName.setForeground(resources.Gui.DARK_SLATE_GRAY);
        labelName.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        attributesPanel.add(labelName, gridBagConstraints);

        inputNombre.setBackground(resources.Gui.DARK_BLUE);
        inputNombre.setFont(fonts.Fonts.TEXT);
        inputNombre.setForeground(resources.Gui.BEIGE);
        inputNombre.setSelectedTextColor(resources.Gui.DARK_BLUE);
        inputNombre.setSelectionColor(resources.Gui.MIDNIGHT_BLUE);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        attributesPanel.add(inputNombre, gridBagConstraints);

        buttonTest.setText("Test");
        buttonTest.setToolTipText("Testea si los campos están bien ingresados.");
        buttonTest.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonTestActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        attributesPanel.add(buttonTest, gridBagConstraints);
        buttonTest.setVisible (code.Main.DEBUG_MODE);

        inputRut.setBackground(resources.Gui.DARK_BLUE);
        inputRut.setForeground(resources.Gui.MIDNIGHT_BLUE);
        inputRut.setFont(fonts.Fonts.TEXT);
        inputRut.setPlaceholder("12345678-9");
        inputRut.setPlaceholderColor(resources.Gui.MIDNIGHT_BLUE);
        inputRut.setSelectedTextColor(resources.Gui.DARK_BLUE);
        inputRut.setSelectionColor(resources.Gui.MIDNIGHT_BLUE);
        inputRut.setTextColor(resources.Gui.BEIGE);
        inputRut.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                inputRutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        attributesPanel.add(inputRut, gridBagConstraints);
        inputRut.reset ();

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 30, 30, 30);
        add(attributesPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTestActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonTestActionPerformed
    {//GEN-HEADEREND:event_buttonTestActionPerformed
        inputsAreCorrect ();

        System.out.println ( "Atributos del empleado:" );
        System.out.println ( "-----------------------" );
        System.out.println ( "Rut: " + rut () );
        System.out.println ( "Nombre: " + nombre () );
        if ( !paterno ().isEmpty () )
        {
            System.out.println ( "Ap. Paterno: " + paterno () );
        }
        if ( !paterno ().isEmpty () )
        {
            System.out.println ( "Ap. Materno: " + materno () );
        }
    }//GEN-LAST:event_buttonTestActionPerformed

    private void inputRutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_inputRutActionPerformed
    {//GEN-HEADEREND:event_inputRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel attributesPanel;
    private javax.swing.JButton buttonTest;
    private javax.swing.JTextField inputMaterno;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputPaterno;
    private components.GTextField inputRut;
    private javax.swing.JLabel labelMaterno;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPaterno;
    private javax.swing.JLabel labelRut;
    private components.TitleBanner titleBar;
    // End of variables declaration//GEN-END:variables

    public boolean inputsAreCorrect ()
    {
        return rutIsCorrect () && nombreIsCorrect ();
    }

    public void resetFields ()
    {
        inputRut.setText ( "" );
        inputPaterno.setText ( "" );
        inputMaterno.setText ( "" );
    }

//<editor-fold defaultstate="collapsed" desc="Getters">
    /**
     * Returns the ID written by the user.
     */
    public String rut ()
    {
        return inputRut.retrieveText ().trim ().toUpperCase ();
    }

    /**
     * Returns the name written by the User.
     */
    public String nombre ()
    {
        return nombreIsCorrect () ?
          inputNombre.getText ().toUpperCase ().trim () : null;
    }

    /**
     * Returns the middle name written by the user.
     */
    public String paterno ()
    {
        return inputPaterno.getText ().toUpperCase ().trim ();
    }

    /**
     * Returns the last name written by the user.
     */
    public String materno ()
    {
        return inputMaterno.getText ().toUpperCase ().trim ();
    }
//</editor-fold>

    private void toggleError (
      JLabel label,
      boolean isCorrect)
    {
        if ( isCorrect )
        {
            label.setForeground ( resources.Gui.DARK_SLATE_GRAY );
        }
        else
        {
            label.setForeground ( resources.Gui.CRIMSON );
        }
    }

    private boolean rutIsCorrect ()
    {
        String rutRegex = "^[0-9]+-[0-9K]$";
        String rut = inputRut.retrieveText ().trim ().toUpperCase ();
        boolean isCorrect = rut.matches ( rutRegex );
        
        toggleError ( labelRut, isCorrect );

        return isCorrect;
    }

    private boolean nombreIsCorrect ()
    {

        String textRegex = "^[A-ZÁÉÍÓÚÑ]+$";
        String name = inputNombre.getText ().trim ().toUpperCase ();
        boolean isCorrect = name.matches ( textRegex );

        toggleError ( labelName, isCorrect );

        return isCorrect;
    }

}
